services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: ${ENVIRONMENT}
      NODE_ENV: ${ENVIRONMENT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      HTTP_BASIC_USERNAME: ${ADMIN_USERNAME}
      HTTP_BASIC_PASSWORD: ${ADMIN_PASSWORD}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_MIN_THREADS: 1
      RAILS_MAX_THREADS: 2
      WEB_CONCURRENCY: 2
      CARDS_PER_PLAYER: 10
      CURRENT_GAMES_LIMIT: 10
      CURRENT_GAMES_WINDOW_HOURS: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    deploy:
      resources:
        limits:
          cpus: 1.0     # 100% of 1 core (1.0 cores)
          memory: 1G    # Max RAM
    networks:
      - cah_network
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: ${ENVIRONMENT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      HTTP_BASIC_USERNAME: ${ADMIN_USERNAME}
      HTTP_BASIC_PASSWORD: ${ADMIN_PASSWORD}
      RAILS_MIN_THREADS: 1
      RAILS_MAX_THREADS: 2
      WEB_CONCURRENCY: 2
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 512M
    networks:
      - cah_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M
    networks:
      - cah_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 64M
    networks:
      - cah_network

volumes:
  node_modules:

networks:
  cah_network: