---
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
:queues:
  - default
  - rollbar
:schedule:
  delete_old_games:
    cron: "0 * * * *"
    class: "DeleteOldGamesWorker"
    queue: default
